force-app/main/default/objects/Contact/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/contactListController.cls
public with sharing class contactListController {
  @AuraEnabled(cacheable=true)
  public static List<Contact> getcontactListC() {
    List<Contact> conList = [
      SELECT Id, Name, FirstName, LastName, Title, Phone, Email, PhotoUrl
      FROM Contact
      WHERE PhotoUrl != NULL
    ];
    return conList;
  }

  @AuraEnabled(cacheable=true)
  public static List<Contact> getcontactListDataTable() {
    List<Contact> conList = [
      SELECT
        Id,
        Name,
        FirstName,
        LastName,
        Title,
        Phone,
        Email,
        Picture__c,
        Rank__c,
        AccountId,
        Account.Name
      FROM Contact
      WHERE AccountId != NULL
    ];
    return conList;
  }
}